version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: connzect-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: connzect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - connzect_postgres_data:/var/lib/postgresql/data

volumes:
  connzect_postgres_data:
